### ISSUE TITLE
Add project: PySimpleGUI

### ISSUE THREAD

**Issue by PySimpleGUI** [ml-tooling/best-of-python-dev#12]
Not yet on the list

**Project details:**

- Project Name: PySimpleGUI
- Github URL: http://www.PySimpleGUI.com
- Category:  GUIs / User Interface Packages
- License: LGPL3
- Package Managers: pypi:PySimpleGUI pypi:PySimpleGUIQt pypi:PySimpleGUIWeb pypi:PySimpleGUIWx

**Additional context:**

You don't seem to have a category that fits.  There are no GUI/user interface development tools listed so there is no category for me to suggest it be in.

**Comment by LukasMasuch** [comment]
@PySimpleGUI Thanks for your suggestion! We have a gui-development category on our main python list here: https://github.com/ml-tooling/best-of-python#gui-development 

PySimpleGUI is also already added there:
![image](https://user-images.githubusercontent.com/2852129/105636454-c2a2f000-5e68-11eb-9c3b-64ec2a14b66d.png)

**Comment by PySimpleGUI** [comment]
Yea, I realized that after I posed the issue.  I'm sorry about that.

**Comment by PySimpleGUI** [comment]
Oh, btw, there are 4 ports of PySimpleGUI.  You may want to include that those are available on PyPI too.
PySimpleGUI
PySimpleGUIQt
PySimpleGUIWeb
PySimpleGUIWx

**Comment by LukasMasuch** [comment]
@PySimpleGUI No problem :) Currently, only one pypi project can be associated with one project. I will take this in the backlog and see if I find a good solution to associate multiple pypi dependencies.

**Comment by PySimpleGUI** [comment]
Your speed of handling issues is FANTASTIC and to be commended.  Love it when support is an integral part of a project.

**Comment by LukasMasuch** [comment]
Closing this for now. The state of this feature can be tracked [here](https://github.com/best-of-lists/best-of-generator/issues/32). Once we have implemented something in the generator, we will update PySimpleGUI.
