### ISSUE TITLE
Add project: xdoctest

### ISSUE THREAD

**Issue by Erotemic** [ml-tooling/best-of-python-dev#5]
**Project details:**
The xdoctest package is a re-write of Python's builtin doctest module. It replaces the old regex-based parser with a new abstract-syntax-tree based parser (using Python's ast module). The goal is to make doctests easier to write, simpler to configure, and encourage the pattern of test driven development.

- Project Name: xdoctest 
- Github URL: https://pypi.org/project/xdoctest/
- Category:  testing
- License: Apache License 2.0
- Package Managers: pypi:xdoctest conda:conda-forge/xdoctest

**Additional context:**

Xdoctest was featured at [PyCon2020](https://www.youtube.com/watch?v=CUjCqOw_oFk) and in [Hypermodern Python](https://medium.com/@cjolowicz/hypermodern-python-5-documentation-13219991028c) tutorial series.

**Comment by LukasMasuch** [comment]
@Erotemic Thanks for the suggestion, xdoctest will be included in the next update.
