### ISSUE TITLE
Add project: snoop

### ISSUE THREAD

**Issue by alexmojaki** [ml-tooling/best-of-python-dev#8]
**Project details:**

- Project Name: snoop
- Github URL: https://github.com/alexmojaki/snoop
- Category:  Debugging Tools
- License: MIT
- Package Managers: pypi:snoop

**Additional context:**

snoop is an alternative to pysnooper. While I may be biased, I do think it's significantly better, and I've explained why in detail here: https://github.com/alexmojaki/snoop/wiki/Comparison-to-PySnooper

While pysnooper has many more stars, AFAICT this comes down to luck and the GitHub trending page in its early days, or at least better marketing.

**Comment by LukasMasuch** [comment]
@alexmojaki Thanks for the contribution :) I just added it to the list!
