### ISSUE TITLE
Add project: rich

### ISSUE THREAD

**Issue by alexmojaki** [ml-tooling/best-of-python-dev#9]
**Project details:**

- Project Name: rich
- Github URL: https://github.com/willmcgugan/rich
- Category:  Logging
- License: MIT
- Package Managers: pypi:rich, conda:rich

**Additional context:**

Rich has features of many of the projects in that category. In particular it has great traceback rendering.

**Comment by LukasMasuch** [comment]
@alexmojaki thanks for the contribution. Rich is also added to the best-of-python list [here](https://github.com/ml-tooling/best-of-python#cli-development). But I think it fits on this list as well.

**Comment by alexmojaki** [comment]
Thanks for accepting my contributions! I was surprised that you didn't have rich, but I agree with your final assessment.
